version: '3.8'

services:
  api:
    build:
    ports:
    - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=ROOT
      - SPRING_DATASOURCE_PASSWORD=ROOT

    mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql 