access-token:
    private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
    private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
    profiles:
        active: dev
    data:
        mongodb:
            uri: mongodb+srv://feelipechs:<db_password>@cluster0.q1ktz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            database: ${MONGODB_DB}
logging:
level:
    org.springframework.security: DEBUG

# spring:
#     data:
#         mongodb:
#             uri: mongodb://feelipechs:<db_password>@cluster0.q1ktz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#             database: <dbname>

# logging:
#     level:
#         org.springframework.security: DEBUG

# ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
# ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
# REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
# REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
# MONGODB_HOST: "localhost"
# MONGODB_PORT: "27017"
# MONGODB_DB: "db1"



# F9z7AoAFUmRGmQbI feelipechs
# mongodb+srv://feelipechs:<db_password>@cluster0.q1ktz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
